### ISSUE TITLE
Text cursor

### ISSUE THREAD

**Issue by farmaazon** [luna/basegl#68]
### Summary
Implement a possibly multilined cursor in text component. This task includes displaying cursors on screen.

### Specification
 The api should support adding a new multicursor, or replace all with a new single one. 

### Acceptance Criteria & Test Cases
An example (or web_test) with blinking cursors

**Comment by wdanilo** [comment]
Adam, we should implement a text cursor using our buffer management system. Let's have a chat before you do it, please.
